# -*- coding: utf-8 -*-
"""Cross_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cCVrL7wNQXBLLKPByv4jwtkYORa0Y6Lg
"""

# 1. IMPORTS

import os
import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate

# 2. CONFIGURATION

DATA_PATH = '/content/drive/MyDrive/archiveData/'
FILES = [
    'Monday-WorkingHours.pcap_ISCX.csv',
    'Tuesday-WorkingHours.pcap_ISCX.csv',
    'Wednesday-workingHours.pcap_ISCX.csv',
    'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
    'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
]
RANDOM_STATE = 42

# 3. DATA LOADING

def load_data(path, files):
    """Load and concatenate all CSV files."""
    drive.mount('/content/drive', force_remount=True)
    df_list = [pd.read_csv(os.path.join(path, f)) for f in files]
    return pd.concat(df_list, ignore_index=True)

# 4. DATA CLEANING

def clean_data(df):
    df = df.copy()
    df.columns = df.columns.str.strip()
    df['Label'] = (df['Label'] != 'BENIGN').astype(int)
    numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
    if 'Label' not in numeric_cols:
        numeric_cols.append('Label')
    df = df[numeric_cols]
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df = df[(df.drop('Label', axis=1).abs() < 1e10).all(axis=1)]
    df.dropna(inplace=True)
    return df

# 5. FEATURE / TARGET SPLIT

def split_features_target(df):
    """Separate features and target variable."""
    X = df.drop('Label', axis=1)
    y = df['Label']
    return X, y

# 6. MODEL PIPELINE
def build_pipeline():
    """Create preprocessing + model pipeline."""
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', SGDClassifier(
            class_weight='balanced',
            random_state=RANDOM_STATE,
            max_iter=1000,
            tol=1e-3
        ))
    ])

# 7. EVALUATION

def evaluate_model(pipeline, X, y, cv_splits=3):
    """Run stratified cross-validation and print results."""
    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=RANDOM_STATE)
    scoring = ['f1', 'recall', 'precision', 'accuracy']
    results = cross_validate(pipeline, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    print("=" * 50)
    print(f"CROSS-VALIDATION RESULTS ({cv_splits}-Fold Stratified)")
    print("=" * 50)
    for metric in scoring:
        scores = results['test_' + metric]
        print(f"{metric.upper():12} | Mean: {scores.mean():.4f} | Std: {scores.std():.4f}")
    print("=" * 50)

    return results

# 8. MAIN EXECUTION

if __name__ == "__main__":
    print("Loading data...")
    df = load_data(DATA_PATH, FILES)
    print(f"Raw shape: {df.shape}")

    print("Cleaning data...")
    df = clean_data(df)
    print(f"Cleaned shape: {df.shape}")
    print(f"Label distribution:\n{df['Label'].value_counts()}")

    # SAMPLE DATASET (start small to avoid RAM crash)
    df_sample = df.sample(n=200000, random_state=RANDOM_STATE)
    print(f"Sampled shape: {df_sample.shape}")

    X, y = split_features_target(df_sample)

    print(f"\nFeatures: {X.shape[1]} | Samples: {X.shape[0]}")
    print(f"NaN count: {X.isna().sum().sum()} | Inf count: {np.isinf(X).sum().sum()}")

    pipeline = build_pipeline()
    metrics = evaluate_model(pipeline, X, y, cv_splits=3)  #  3 folds

#Step 1: RandomForestClassifier Model
from sklearn.ensemble import RandomForestClassifier

def build_pipeline_rf():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', RandomForestClassifier(
            n_estimators=100,
            class_weight='balanced',
            random_state=RANDOM_STATE,
            n_jobs=-1
        ))
    ])

# Step 2: Feature Selection
from sklearn.feature_selection import SelectKBest, f_classif

def build_pipeline_fs():
    return Pipeline([
        ('select', SelectKBest(score_func=f_classif, k=30)),  # keep top 30
        ('scaler', RobustScaler()),
        ('model', SGDClassifier(class_weight='balanced', random_state=RANDOM_STATE))
    ])

#Step 3: Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__alpha': [0.0001, 0.001, 0.01],
    'model__penalty': ['l2', 'l1', 'elasticnet']
}

grid = GridSearchCV(build_pipeline(), param_grid, cv=3, scoring='f1', n_jobs=-1)
grid.fit(X, y)
print("Best params:", grid.best_params_)

#Step 4: Handle Class Imbalance More Aggressively
from imblearn.over_sampling import SMOTE

def build_pipeline_smote():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('smote', SMOTE(random_state=RANDOM_STATE)),
        ('model', SGDClassifier(random_state=RANDOM_STATE))
    ])

# 1. IMPORTS

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt   # Added for visualization
from google.colab import drive
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier   #  Added RandomForest
from sklearn.model_selection import StratifiedKFold, cross_validate

# 6. MODEL PIPELINE (RandomForest)

def build_pipeline_rf():
    """RandomForest pipeline with scaling."""
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', RandomForestClassifier(
            n_estimators=100,
            class_weight='balanced',
            random_state=RANDOM_STATE,
            n_jobs=-1
        ))
    ])

# 7. EVALUATION + VISUALIZATION

def evaluate_model_with_plot(pipeline, X, y, cv_splits=3):
    """Run stratified CV and visualize accuracy results."""
    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=RANDOM_STATE)
    scoring = ['f1', 'recall', 'precision', 'accuracy']
    results = cross_validate(pipeline, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    print("=" * 50)
    print(f"CROSS-VALIDATION RESULTS ({cv_splits}-Fold Stratified)")
    print("=" * 50)
    for metric in scoring:
        scores = results['test_' + metric]
        print(f"{metric.upper():12} | Mean: {scores.mean():.4f} | Std: {scores.std():.4f}")
    print("=" * 50)

    # 🔧 Visualization of accuracy per fold
    acc_scores = results['test_accuracy']
    plt.figure(figsize=(6,4))
    plt.plot(range(1, cv_splits+1), acc_scores, marker='o', linestyle='--', color='blue')
    plt.title("RandomForest Accuracy per Fold")
    plt.xlabel("Fold")
    plt.ylabel("Accuracy")
    plt.ylim(0,1)
    plt.grid(True)
    plt.show()

    return results

# 8. MAIN EXECUTION

if __name__ == "__main__":
    print("Loading data...")
    df = load_data(DATA_PATH, FILES)
    print(f"Raw shape: {df.shape}")

    print("Cleaning data...")
    df = clean_data(df)
    print(f"Cleaned shape: {df.shape}")
    print(f"Label distribution:\n{df['Label'].value_counts()}")

    #  SAMPLE DATASET (start small)
    df_sample = df.sample(n=200000, random_state=RANDOM_STATE)
    print(f"Sampled shape: {df_sample.shape}")

    X, y = split_features_target(df_sample)

    print(f"\nFeatures: {X.shape[1]} | Samples: {X.shape[0]}")
    print(f"NaN count: {X.isna().sum().sum()} | Inf count: {np.isinf(X).sum().sum()}")

    pipeline_rf = build_pipeline_rf()
    metrics_rf = evaluate_model_with_plot(pipeline_rf, X, y, cv_splits=3)

#1. Logistic Regression
from sklearn.linear_model import LogisticRegression

def build_pipeline_lr():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', LogisticRegression(
            class_weight='balanced',
            solver='saga',
            max_iter=1000,
            random_state=RANDOM_STATE,
            n_jobs=-1
        ))
    ])

#2. XGBoost
!pip install xgboost

from xgboost import XGBClassifier

def build_pipeline_xgb():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', XGBClassifier(
            scale_pos_weight=(y.value_counts()[0]/y.value_counts()[1]), # imbalance fix
            n_estimators=200,
            max_depth=8,
            learning_rate=0.1,
            random_state=RANDOM_STATE,
            n_jobs=-1,
            use_label_encoder=False,
            eval_metric='logloss'
        ))
    ])

#3. LightGBM
!pip install lightgbm

from lightgbm import LGBMClassifier

def build_pipeline_lgbm():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', LGBMClassifier(
            class_weight='balanced',
            n_estimators=200,
            max_depth=-1,
            learning_rate=0.1,
            random_state=RANDOM_STATE,
            n_jobs=-1
        ))
    ])

#Logistic Regression
pipeline_lr = build_pipeline_lr()
metrics_lr = evaluate_model_with_plot(pipeline_lr, X, y, cv_splits=2)

#XGBoost
pipeline_xgb = build_pipeline_xgb()
metrics_xgb = evaluate_model_with_plot(pipeline_xgb, X, y, cv_splits=2)

#Run LightGBM
pipeline_lgbm = build_pipeline_lgbm()
metrics_lgbm = evaluate_model_with_plot(pipeline_lgbm, X, y, cv_splits=2)

"""**Logistic Regression on 50k rows with 2‑fold cross‑validation**"""

import os
import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_validate
import matplotlib.pyplot as plt

#2. Logistic Regression Pipeline
def build_pipeline_lr():
    return Pipeline([
        ('scaler', RobustScaler()),
        ('model', LogisticRegression(
            class_weight='balanced',
            solver='saga',
            max_iter=1000,
            random_state=42,
            n_jobs=-1
        ))
    ])

#3. Evaluation with Visualization
def evaluate_model_with_plot(pipeline, X, y, cv_splits=2):
    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=42)
    scoring = ['f1', 'recall', 'precision', 'accuracy']
    results = cross_validate(pipeline, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    print("=" * 50)
    print(f"CROSS-VALIDATION RESULTS ({cv_splits}-Fold Stratified)")
    print("=" * 50)
    for metric in scoring:
        scores = results['test_' + metric]
        print(f"{metric.upper():12} | Mean: {scores.mean():.4f} | Std: {scores.std():.4f}")
    print("=" * 50)

    # Plot accuracy per fold
    acc_scores = results['test_accuracy']
    plt.figure(figsize=(6,4))
    plt.plot(range(1, cv_splits+1), acc_scores, marker='o', linestyle='--', color='green')
    plt.title("Logistic Regression Accuracy per Fold")
    plt.xlabel("Fold")
    plt.ylabel("Accuracy")
    plt.ylim(0,1)
    plt.grid(True)
    plt.show()

    return results

#4. Main Execution (with 50k sample)
if __name__ == "__main__":
    print("Loading data...")
    drive.mount('/content/drive', force_remount=True)
    files = [
        'Monday-WorkingHours.pcap_ISCX.csv',
        'Tuesday-WorkingHours.pcap_ISCX.csv',
        'Wednesday-workingHours.pcap_ISCX.csv',
        'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
    ]
    path = '/content/drive/MyDrive/archiveData/'
    df_list = [pd.read_csv(os.path.join(path, f)) for f in files]
    df = pd.concat(df_list, ignore_index=True)

    print(f"Raw shape: {df.shape}")

    # Clean
    df.columns = df.columns.str.strip()
    df['Label'] = (df['Label'] != 'BENIGN').astype(int)
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    # 🔧 Sample 50k rows
    df_sample = df.sample(n=50000, random_state=42)
    print(f"Sampled shape: {df_sample.shape}")

    X = df_sample.drop('Label', axis=1).select_dtypes(include=['number'])
    y = df_sample['Label']

    pipeline_lr = build_pipeline_lr()
    metrics_lr = evaluate_model_with_plot(pipeline_lr, X, y, cv_splits=2)

"""**Then test XGBoost separately**"""

!pip install xgboost

import os
import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import StratifiedKFold, cross_validate
import matplotlib.pyplot as plt
from xgboost import XGBClassifier

#2. Build XGBoost Pipeline
def build_pipeline_xgb(y):
    """XGBoost pipeline with imbalance fix."""
    imbalance_ratio = y.value_counts()[0] / y.value_counts()[1]
    return Pipeline([
        ('scaler', RobustScaler()),  # optional, XGB can handle raw values
        ('model', XGBClassifier(
            scale_pos_weight=imbalance_ratio,
            n_estimators=200,
            max_depth=8,
            learning_rate=0.1,
            random_state=42,
            n_jobs=-1,
            use_label_encoder=False,
            eval_metric='logloss'
        ))
    ])

#3. Evaluation with Visualization
def evaluate_model_with_plot(pipeline, X, y, cv_splits=2):
    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=42)
    scoring = ['f1', 'recall', 'precision', 'accuracy']
    results = cross_validate(pipeline, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    print("=" * 50)
    print(f"CROSS-VALIDATION RESULTS ({cv_splits}-Fold Stratified)")
    print("=" * 50)
    for metric in scoring:
        scores = results['test_' + metric]
        print(f"{metric.upper():12} | Mean: {scores.mean():.4f} | Std: {scores.std():.4f}")
    print("=" * 50)

    # Plot accuracy per fold
    acc_scores = results['test_accuracy']
    plt.figure(figsize=(6,4))
    plt.plot(range(1, cv_splits+1), acc_scores, marker='o', linestyle='--', color='orange')
    plt.title("XGBoost Accuracy per Fold")
    plt.xlabel("Fold")
    plt.ylabel("Accuracy")
    plt.ylim(0,1)
    plt.grid(True)
    plt.show()

    return results

#4. Main Execution (50k sample, 2 folds)
if __name__ == "__main__":
    print("Loading data...")
    drive.mount('/content/drive', force_remount=True)
    files = [
        'Monday-WorkingHours.pcap_ISCX.csv',
        'Tuesday-WorkingHours.pcap_ISCX.csv',
        'Wednesday-workingHours.pcap_ISCX.csv',
        'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
    ]
    path = '/content/drive/MyDrive/archiveData/'
    df_list = [pd.read_csv(os.path.join(path, f)) for f in files]
    df = pd.concat(df_list, ignore_index=True)

    print(f"Raw shape: {df.shape}")

    # Clean
    df.columns = df.columns.str.strip()
    df['Label'] = (df['Label'] != 'BENIGN').astype(int)
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    # 🔧 Sample 50k rows
    df_sample = df.sample(n=50000, random_state=42)
    print(f"Sampled shape: {df_sample.shape}")

    X = df_sample.drop('Label', axis=1).select_dtypes(include=['number'])
    y = df_sample['Label']

    pipeline_xgb = build_pipeline_xgb(y)
    metrics_xgb = evaluate_model_with_plot(pipeline_xgb, X, y, cv_splits=2)

"""**Compare results to RandomForest**"""

#Step 1: Store Results
metrics_rf = evaluate_model_with_plot(pipeline_rf, X, y, cv_splits=2)
metrics_xgb = evaluate_model_with_plot(pipeline_xgb, X, y, cv_splits=2)

#Step 2: Extract Mean Scores
def extract_means(results):
    return {
        'F1': np.mean(results['test_f1']),
        'Recall': np.mean(results['test_recall']),
        'Precision': np.mean(results['test_precision']),
        'Accuracy': np.mean(results['test_accuracy'])
    }

rf_scores = extract_means(metrics_rf)
xgb_scores = extract_means(metrics_xgb)

#Step 3: Create Comparison Table
import pandas as pd

comparison_df = pd.DataFrame([rf_scores, xgb_scores], index=['RandomForest', 'XGBoost'])
print(comparison_df)

#Step 4: Visualize Side‑by‑Side
import matplotlib.pyplot as plt

comparison_df.plot(kind='bar', figsize=(8,6))
plt.title("Model Comparison: RandomForest vs XGBoost")
plt.ylabel("Score")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.legend(loc='lower right')
plt.grid(axis='y')
plt.show()