# -*- coding: utf-8 -*-
"""Main_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gV_qT36_vT6rV7Cx-eFYjw0MXDUGn52q

**STEP 1 Connect Google Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Step 2 imports libraries**"""

import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
import seaborn as sns

"""**STEP 3 LOAD & MERGE DATASET**"""

import pandas as pd
import glob

path = "/content/drive/MyDrive/archiveData/*.csv"
files = glob.glob(path)

df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

print("Dataset Shape:", df.shape)

"""**STEP 5 HANDLE MISSING & INFINITE VALUES**"""

import numpy as np

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

print("After Cleaning:", df.shape)

"""**STEP 6  SAMPLE DATA**"""

df = df.sample(n=300000, random_state=42)

print("Sampled Shape:", df.shape)

"""**STEP 7 EDA (BASIC)**"""

df.info()
df.describe()

"""**STEP 8 FIX TARGET COLUMN**"""

df['Label'] = df['Label'].apply(lambda x: 'Attack' if x != 'BENIGN' else 'BENIGN')

"""**STEP 9 ENCODE TARGET**"""

df['Label'] = df['Label'].map({'BENIGN': 0, 'Attack': 1})

"""**STEP 10 VISUALIZATION**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
df['Label'].value_counts().plot(kind='bar')
plt.title("Normal vs Attack Distribution")
plt.show()

"""**STEP 11 SPLIT FEATURES & TARGET**"""

X = df.drop('Label', axis=1)
y = df['Label']

"""**STEP 12 CLEAN FEATURES**"""

X = X.replace([np.inf, -np.inf], np.nan)

# Drop columns with too many missing values
X = X.dropna(axis=1, thresh=int(0.7 * len(X)))

# Keep only numeric
X = X.select_dtypes(include=np.number)

# Fill remaining NaN
X = X.fillna(X.median())

"""**STEP 13 REMOVE LOW VARIANCE FEATURES**"""

from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.0)
X_var = selector.fit_transform(X)

cols = X.columns[selector.get_support()]
X = pd.DataFrame(X_var, columns=cols)

"""**STEP 14 LOG TRANSFORMATION**"""

# Ensure no negative values before log
X = X.clip(lower=0)

# Replace inf again (safety)
X = X.replace([np.inf, -np.inf], np.nan)

# Fill NaN safely
X = X.fillna(X.median())

# Apply log transform safely
X_log = np.log1p(X)

X_log = pd.DataFrame(X_log)

X_log = X_log.replace([np.inf, -np.inf], np.nan)
X_log = X_log.fillna(X_log.median())

# Convert to DataFrame (if not already)
X_log = pd.DataFrame(X_log)

# Clip extreme values (IMPORTANT 🔥)
X_log = X_log.clip(lower=X_log.quantile(0.01),
                   upper=X_log.quantile(0.99),
                   axis=1)

"""**STEP 15 POWER TRANSFORMATION**"""

from sklearn.preprocessing import QuantileTransformer
import numpy as np
import pandas as pd

# Convert to DataFrame (safety)
X_log = pd.DataFrame(X_log)

# STEP 1: Replace bad values
X_log = X_log.replace([np.inf, -np.inf], np.nan)

# STEP 2: Fill missing values (IMPORTANT)
X_log = X_log.fillna(X_log.median())

# STEP 3: Clip extreme values (VERY IMPORTANT 🔥)
lower = X_log.quantile(0.01)
upper = X_log.quantile(0.99)
X_log = X_log.clip(lower=lower, upper=upper, axis=1)

# STEP 4: Remove near-constant columns (stability fix - increased threshold for robustness)
X_log = X_log.loc[:, X_log.std() > 0.01]

# STEP 5: Apply Quantile Transformation
qt = QuantileTransformer(output_distribution='normal', random_state=42)
X_transformed = qt.fit_transform(X_log)

# Final dataset
X_final = pd.DataFrame(X_transformed, columns=X_log.columns)

print(np.isnan(X_final).sum().sum())
print(np.isinf(X_final).sum().sum())

"""**STEP 16 CHECK SKEWNESS**"""

skewness_final = X_final.skew().sort_values(ascending=False)
print(skewness_final.head(10))

"""**Drop Highly Skewed Columns**"""

skewness = X_final.skew()

# Select features with skewness > 5
high_skew_cols = skewness[skewness > 5].index

print("Dropping:", list(high_skew_cols))

# Drop them
X_final = X_final.drop(columns=high_skew_cols)

skewness_final = X_final.skew().sort_values(ascending=False)
print(skewness_final.head(10))

"""**Further Clean**"""

skewness = X_final.skew()
high_skew_cols = skewness[skewness > 4].index

X_final = X_final.drop(columns=high_skew_cols)

skewness_final = X_final.skew().sort_values(ascending=False)
print(skewness_final.head(10))

"""**NEXT PHASE MODEL BUILDING**

**STEP 1 SCALE DATA**
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_final)

"""**STEP 2 TRAIN-TEST SPLIT**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

"""**STEP 3  TRAIN MODEL (Random Forest)**"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

"""**STEP 4 EVALUATION**"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Create a publication-quality confusion matrix figure based on provided values

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Given confusion matrix values
cm = np.array([[45282, 7],
               [5, 14706]])

# Labels
labels = ["Benign (0)", "Attack (1)"]

# Plot
fig, ax = plt.subplots(figsize=(6,6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(ax=ax, cmap='Blues', colorbar=True)

# Title and formatting
plt.title("Confusion Matrix for Random Forest Model", fontsize=12)
plt.grid(False)
plt.tight_layout()

plt.show()

"""**STEP 5  CONFUSION MATRIX**

**STEP 6 FEATURE IMPORTANCE (VERY IMPORTANT)**
"""

import matplotlib.pyplot as plt
import numpy as np

# Get feature importance
importances = model.feature_importances_
indices = np.argsort(importances)[-10:]

features = X_final.columns[indices]
values = importances[indices]

plt.figure(figsize=(8,6))
bars = plt.barh(features, values, color="steelblue", edgecolor="black")

# Add numeric labels at the end of each bar
for bar, val in zip(bars, values):
    plt.text(val + 0.002, bar.get_y() + bar.get_height()/2,
             f"{val:.3f}", va='center', fontsize=9)

# Labels
plt.xlabel("Importance")
plt.title("Top 10 Important Features")

plt.tight_layout()
plt.show()

print(X_train.shape)
print(X_test.shape)

"""**Now it's SVM**

**STEP 1 SVM MODEL**
"""

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

svm_model = SVC()

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

"""**STEP 2 XGBOOST MODEL (VERY POWERFUL)**"""

!pip install xgboost

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

"""**STEP 3 CREATE COMPARISON TABLE**"""

rf_acc = accuracy_score(y_test, y_pred)
svm_acc = accuracy_score(y_test, y_pred_svm)
xgb_acc = accuracy_score(y_test, y_pred_xgb)

comparison = pd.DataFrame({
    'Model': ['Random Forest', 'SVM', 'XGBoost'],
    'Accuracy': [rf_acc, svm_acc, xgb_acc]
})

print(comparison)

"""**BETTER TABLE (WITH PRECISION / RECALL)**"""

from sklearn.metrics import precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred):
    return [
        accuracy_score(y_true, y_pred),
        precision_score(y_true, y_pred),
        recall_score(y_true, y_pred),
        f1_score(y_true, y_pred)
    ]

rf_metrics = get_metrics(y_test, y_pred)
svm_metrics = get_metrics(y_test, y_pred_svm)
xgb_metrics = get_metrics(y_test, y_pred_xgb)

comparison = pd.DataFrame({
    'Model': ['Random Forest', 'SVM', 'XGBoost'],
    'Accuracy': [rf_metrics[0], svm_metrics[0], xgb_metrics[0]],
    'Precision': [rf_metrics[1], svm_metrics[1], xgb_metrics[1]],
    'Recall': [rf_metrics[2], svm_metrics[2], xgb_metrics[2]],
    'F1 Score': [rf_metrics[3], svm_metrics[3], xgb_metrics[3]]
})

print(comparison)

"""**OPTIONAL VISUAL COMPARISON (FIGURE)**"""

comparison.set_index('Model')[['Accuracy','Precision','Recall','F1 Score']].plot(kind='bar')
plt.title("Model Comparison")
plt.xticks(rotation=0)
plt.show()

"""**Model Comparison Bar Chart (VERY IMPORTANT)**"""

# Create a publication-quality model comparison bar chart

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Given data
data = {
    "Model": ["Random Forest", "SVM", "XGBoost"],
    "Accuracy": [0.999800, 0.999750, 0.999867],
    "Precision": [0.999524, 0.999456, 0.999660],
    "Recall": [0.999660, 0.999524, 0.999796],
    "F1 Score": [0.999592, 0.999490, 0.999728]
}

df = pd.DataFrame(data)

# Set index
df.set_index("Model", inplace=True)

# Plot
fig, ax = plt.subplots(figsize=(8,6))
df.plot(kind='bar', ax=ax)

# Formatting
plt.title("Performance Comparison of Machine Learning Models", fontsize=12)
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.ylim(0.9993, 1.0)  # zoomed for clarity
plt.legend(loc='lower right')
plt.tight_layout()

plt.show()

"""**Accuracy Comparison Only (Cleaner Figure)**"""

comparison.plot(x='Model', y='Accuracy', kind='bar', legend=False)

plt.title("Accuracy Comparison of Models")
plt.ylabel("Accuracy")
plt.xticks(rotation=0)
plt.show()

# Simulate a dataset similar in structure (numeric features) to generate the heatmap
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Create synthetic data (since original df is not available here)
np.random.seed(42)
data = np.random.rand(1000, 20)
df = pd.DataFrame(data, columns=[f'Feature_{i}' for i in range(20)])

# Compute correlation
corr = df.corr(numeric_only=True)

# Plot heatmap as per user's code
plt.figure(figsize=(12,10))
sns.heatmap(corr, cmap="coolwarm", vmin=-1, vmax=1, annot=False)
plt.title("Correlation Heatmap of Numeric Features")
plt.tight_layout()
plt.show()

"""**Histogram (Feature Distribution)**"""

plt.figure(figsize=(6,4))
df['Flow Duration'].hist(bins=50)
plt.title("Distribution of Flow Duration")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

"""**Boxplot (Outlier Detection)**"""

plt.figure(figsize=(6,4))
sns.boxplot(x=df['Flow Duration'])
plt.title("Outlier Detection in Flow Duration")
plt.show()

"""**Correlation Heatmap**"""

import numpy as np
import matplotlib.pyplot as plt

# Extract the data
data = df['Flow Duration']

plt.figure(figsize=(8,6))

# Use log-spaced bins from 1 up to max value
bins = np.logspace(np.log10(1), np.log10(data.max()), 50)

plt.hist(data, bins=bins, color='steelblue', edgecolor='black')

# Apply log scale to x-axis
plt.xscale('log')

# Labels and title
plt.xlabel("Flow Duration (log scale)")
plt.ylabel("Frequency")
plt.title("Distribution of Flow Duration (Log Scale)")

# Add grid for clarity
plt.grid(True, which="both", linestyle="--", linewidth=0.5)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True).iloc[:20, :20], cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Enhancing histogram of 'Flow Duration' with mean/median lines and lognormal fit for publication
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import lognorm
import os

# Ensure output directory exists
os.makedirs("/mnt/data", exist_ok=True)

# Simulate example data similar to 'Flow Duration' (replace with actual df['Flow Duration'] in real use)
np.random.seed(42)
simulated_data = np.random.lognormal(mean=12, sigma=1.0, size=100000)
df = pd.DataFrame({'Flow Duration': simulated_data})

# Extract the data
data = df['Flow Duration']

# Compute mean and median
mean_val = data.mean()
median_val = data.median()

# Fit a lognormal distribution
shape, loc, scale = lognorm.fit(data, floc=0)  # Fix location to 0 for standard lognormal

# Create log-spaced bins
bins = np.logspace(np.log10(data.min()), np.log10(data.max()), 50)

# Plot histogram
plt.figure(figsize=(10, 6))
counts, bins, patches = plt.hist(data, bins=bins, density=True, color='skyblue', edgecolor='black', alpha=0.7, label='Histogram')

# Plot fitted lognormal PDF
x = np.logspace(np.log10(data.min()), np.log10(data.max()), 1000)
pdf = lognorm.pdf(x, shape, loc=loc, scale=scale)
plt.plot(x, pdf, 'r-', lw=2, label='Fitted Lognormal PDF')

# Add mean and median lines
plt.axvline(mean_val, color='green', linestyle='--', linewidth=2, label=f'Mean = {mean_val:.2e}')
plt.axvline(median_val, color='purple', linestyle='-.', linewidth=2, label=f'Median = {median_val:.2e}')

# Log scale and labels
plt.xscale('log')
plt.xlabel("Flow Duration (log scale)")
plt.ylabel("Density")
plt.title("Distribution of Flow Duration with Lognormal Fit")
plt.grid(True, which="both", linestyle="--", linewidth=0.5)
plt.legend()
plt.tight_layout()

# Save the figure
output_path = "/mnt/data/flow_duration_histogram_lognormal.png"
plt.savefig(output_path)

print(f"Enhanced histogram with mean, median, and lognormal fit saved as {output_path}")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Extract the data
data = df['Flow Duration']

plt.figure(figsize=(8,6))

# Create boxplot
sns.boxplot(x=data, color='steelblue')

# Apply log scale to x-axis
plt.xscale('log')

# Labels and title
plt.xlabel("Flow Duration (log scale)")
plt.title("Box Plot of Flow Duration (Log Scale)")

# Add grid for clarity
plt.grid(True, which="both", linestyle="--", linewidth=0.5)

plt.tight_layout()
plt.show()